workflows:
  android-app:
    name: Android App Build
    working_directory: .  # Root of the repository
    environment:
      java: 11 # Request Java 11
    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android App
        script: |
          chmod +x ./gradlew
          ./gradlew assembleDebug --no-daemon
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - aapex873@gmail.com # Replace with your email address
        notify:
          success: true
          failure: true
