workflows:
  android-app:
    name: Android App Build
    # Update this line to match the folder structure in GitHub
    working_directory: ubuntu/AndroidApp 
    environment:
      java: 11 # Request Java 11
    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android App
        script: |
          ./gradlew assembleDebug --no-daemon
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - your_email@example.com # Replace with your email address
        notify:
          success: true
          failure: true
