workflows:
  android-app:
    name: Android App Build
    working_directory: .  # Root of the repository
    environment:
      java: 11 # Request Java 11
      # Explicitly add wrapper jar to classpath environment variable
      vars:
         GRADLE_OPTS: "-Djava.class.path=gradle/wrapper/gradle-wrapper.jar"
    scripts:
      - name: Check files
        script: |
          echo "Listing root directory:"
          ls -la
          echo "Listing gradle/wrapper directory:"
          ls -la gradle/wrapper
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android App
        script: |
          chmod +x ./gradlew
          # Try running gradle directly using the wrapper jar in classpath
          java -cp gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain assembleDebug --no-daemon --stacktrace
          # Fallback to standard gradlew command if the above fails
          # ./gradlew assembleDebug --no-daemon --stacktrace
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - aapex873@gmail.com # Replace with your email address
        notify:
          success: true
          failure: true
